name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular Application
        run: |
          npx ng build --configuration production --base-href "/lukalaAvant-app-new/"

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/my-drop-down-app/browser

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4